#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=align-tilts
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=4g
#SBATCH --gpus 1
#
#SBATCH --time=24:00:00
#

module load motioncor2
module load imod

align-tilts
