#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-build-sets
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=1:00:00
#

. e2-header

e2spt_buildsets.py --allparticles

. e2-footer
