#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-extract-particles
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=100
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

#label=$1; shift
#boxsz=$1; shift

. e2-header

echo "Extracting particles
$@" | notify

e2spt_extract.py --threads=${SLURM_CPUS_ON_NODE} $@
#e2spt_extract.py --boxsz_unbin=${boxsz:-"-1"} --threads=${SLURM_CPUS_ON_NODE} --label=$label --maxtilt=120 --padtwod=2.0 --alltomograms --shrink=1.0 --tltkeep=1.0 --rmbeadthr=-1.0 --curves=-1 --curves_overlap=0.5 --compressbits=8

. e2-footer
