#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2tomogram
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

sptcls_str=""
sptcls=`find-sptcls` && sptcls_str="Sptcls: $sptcls"

echo "Finished $SLURM_JOB_NAME on $PROJECT

Job: $SLURM_JOB_ID
Node: $NODENAME
$sptcls_str

" | notify
