#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2mpi-refinemulti
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=128
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2g
#SBATCH --exclude=tur[000-026],volt[000-005],ampt[000-020],psc[000-009]
#
#SBATCH --time=10-00:00:00
#

#ref="$1"; shift
#particles="$1"; shift
#nref="${1:+--nref $1}"; shift

. e2-header

echo "$@" | sed 's/--/\n\n--/' | notify
#Reference: $ref
#Particles: $particles
#Nref: $nref" | notify

#e2spt_refinemulti_new.py $ref --ptcls $particles $nref --niter 10 --maxres 20 --parallel=mpi:128:${E2_LSCRATCH}
e2spt_refinemulti_new.py --parallel=mpi:${SLURM_NTASKS}:${E2_LSCRATCH} $@

. e2-footer
