#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-mpi-initial-model
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=64
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

particles="$1"; shift
ncls="$1"; shift

. e2-header

if [[ -z "$particles" ]]; then
  echo "Need to specify particles" | notify
  exit 1
fi

echo "Processing particles in ${particles}" | notify

e2spt_sgd_new.py ${particles} --res=50.0 --niter=10 --shrink=2 --parallel=mpi:200:${E2_LSCRATCH} --ncls=${ncls:-"1"} --batch=48 --learnrate=0.2 --sym=c1
#e2bdb.py -cF

. e2-footer
