#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-refine
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=256
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=5-00:00:00
#

#set -Eexo pipefail

#particles=$1; shift
#ref=$1; shift
#args="$@"; shift $#

. e2-header

. ~/opt/eman2-unstable/bin/activate

#e2spt_refine_new.py --parallel=mpi:${SLURM_NTASKS}:${E2_LSCRATCH} $@

e2spt_refine_new.py --startres=50.0 --sym=c1 --iters=p,p,p,t,p,p,t,r,d --keep=0.95 --maxres=0.0 --minres=0.0 --parallel=mpi:256:${E2_LSCRATCH} --threads=10 --m3dthread $@
#e2spt_refine_new.py --ptcls=$particles --ref=$ref --startres=50.0 --sym=c1 --iters=p,p,p,t,p,p,t,r,d --keep=0.95 --maxres=0.0 --minres=0.0 --parallel=mpi:256:${E2_LSCRATCH} --threads=10 --m3dthread $args | notify

. e2-footer
