#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-mpi-extract-particles
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=20
#SBATCH --cpus-per-task=12
#SBATCH --mem-per-cpu=4g
#SBATCH --exclude=tur[000-026],volt[000-005],ampt[000-020]
#
#SBATCH --time=24:00:00
#

label=$1; shift
boxsz=$1; shift

. e2-header

echo "Extracting particles for label $label" | notify

e2spt_extract.py --boxsz_unbin=${boxsz:-"-1"}  --label=$label --maxtilt=120 --padtwod=2.0 --alltomograms --shrink=1.0 --tltkeep=1.0 --rmbeadthr=-1.0 --curves=-1 --curves_overlap=0.5 --compressbits=8 --parallel=mpi:${SLURM_NTASKS}:${E2_LSCRATCH}

cp -av ${E2_LSCRATCH} /scratch/acjs/

. e2-footer
