#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2mpirefinemulti
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=128
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

ref="$1"; shift
particles="$1"; shift

. e2-header

echo "
Reference: $ref
Particles: $particles" | notify

e2spt_refinemulti_new.py $ref --ptcls $particles --niter 10 --maxres 20 --parallel=mpi:128:/lscratch/acjs/ 

. e2-footer
