#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2projectmanager
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --gpus=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=24g
#
#SBATCH --time=7-00:00:00
#

#. ~/opt/eman2-unstable/bin/activate

. ~/opt/miniconda3/bin/activate eman2

. e2-header

vncserver
export DISPLAY="$(ls -1 --sort=time ~/.vnc/ | head -n 1 | sed -r 's/.*(:[0-9]+).log/\1/')"

e2projectmanager.py &

xterm

# Close VNC server and cleanup
vncserver -kill $DISPLAY

. e2-footer
