#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2refinemulti
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

#ref="$1"; shift
#particles="$1"; shift
#nref="$1"; shift

. e2-header

#echo "
#Reference: $ref
#Particles: $particles
#Nref: $nref" | notify
echo "$@" | sed 's/--/\n\n--/' | notify

#e2spt_refinemulti_new.py $ref --ptcls $particles --nref $nref --niter 10 --maxres 20 --parallel threads:32
e2spt_refinemulti_new.py --parallel thread:${SLURM_CPUS_ON_NODE} $@


. e2-footer
