#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2tomopreproc
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

. e2-header

find ./tomograms -name '*_bin4.hdf' | parallel -j $SLURM_CPUS_PER_TASK e2tomoseg_preproc.py {} --proctag=preproc --proc1=filter.lowpass.gauss:cutoff_abs=.25 --proc2=filter.highpass.gauss:cutoff_pixels=5 --proc3=normalize --proc4=threshold.clampminmax.nsigma:nsigma=3 

. e2-footer
