#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2tomogram
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=8g
#
#SBATCH --time=24:00:00
#

tiltangle="$1"; shift

. e2-header

rawtlt=""
if [[ -d ./rawtlt ]]; then
  rawtlt="--rawtlt=rawtlt"
fi

mdoc=""
if [[ -d ./mdocs ]]; then
  mdocs="--mdoc=mdocs"
fi

e2tomogram.py --alltiltseries --zeroid=-1 --tltstep=2.0 ${rawtlt} ${mdoc} --npk=20 --tltax="${tiltangle}" --tltkeep=0.9 --outsize=1k --niter=2,1,1,1 --bytile --notmp --pkkeep=0.9 --compressbits=8 --clipz=512 --bxsz=32 --filterres=40.0 --rmbeadthr=10.0 --threads=32 --patchtrack=2 --correctrot --extrapad --moretile --xdrift --autoclipxy

. e2-footer
