#!/bin/bash

e2proc3d.py --meanshrink 4  --process filter.lowpass.gauss:cutoff_abs=.25 --process filter.highpass.gauss:cutoff_pixels=5 --process normalize --process threshold.clampminmax.nsigma:nsigma=3 $1 ${1%.*}_bin4_filtered.mrc
