#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2spt_refinemulti_new
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

. ~/opt/eman2-unstable/bin/activate

e2spt_refinemulti_new.py sptsgd_00/output_cls0.hdf --ptcls ./sets/pure_blob.lst --niter 5 --nref 3 --parallel thread:24
