#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-box-ref
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=128
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

set -Eeuo pipefail

ref=$1
label=$2
shift 2

. ~/opt/eman2-unstable/bin/activate

tomos=`find tomograms/ -name '*.hdf'`
echo Using tomograms $tomos

e2spt_tempmatch.py $tomos --reference=$ref --label=$label --nptcl=500 --dthr=-1.0 --vthr=5.0 --delta=30.0 --sym=c1 --rmedge --rmgold --boxsz=-1 --threads=128
