#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-extract-particles
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=1:00:00
#

label=$1; shift
project="`pwd | sed 's/.*work\///g'`"

echo "Beginning set build on $project" | notify_slack -username "SDF $project"

. ~/opt/eman2-unstable/bin/activate

e2spt_buildsets.py --allparticles

echo "Finished set build on $project

`times`" | notify_slack -username "SDF $project"
