#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-extract-particles
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

label=$1; shift
project="`pwd | sed 's/.*work\///g'`"

echo "Beginning particle extraction on $project" | notify_slack -username "SDF $project"

. ~/opt/eman2-unstable/bin/activate

e2spt_extract.py --boxsz_unbin=-1 --threads=64 --label=$label --maxtilt=120 --padtwod=2.0 --alltomograms --shrink=1.0 --tltkeep=1.0 --rmbeadthr=-1.0 --curves=-1 --curves_overlap=0.5 --compressbits=8

echo "Finished particle extraction on $project

`times`" | notify_slack -username "SDF $project"
