#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2tomogram
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

PROJECT="`pwd | sed 's/.*work\///g'`"
NODENAME=${SLURM_JOB_NODELIST[$SLURM_NODEID]}

notify() {
  notify_slack -username "SDF[$NODENAME] $PROJECT"
}

echo "Beginning $SLURM_JOB_NAME on $PROJECT

Job: $SLURM_JOB_ID
Node: $NODENAME

Running on $SLUR_JOB_NUM_NODES nodes with $SLURM_NTASKS tasks" | notify
