#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-initial-model
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=64
#SBATCH --mem-per-cpu=8g
#
#SBATCH --time=24:00:00
#

. ~/opt/eman2-unstable/bin/activate

e2spt_sgd_new.py sets/mmcpn_curated.lst --res=50.0 --niter=100 --shrink=1 --parallel=thread:64 --ncls=1 --batch=12 --learnrate=0.2 --sym=c1
