#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2-mpi
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=2
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#


. ~/opt/eman2-unstable/bin/activate
module load openmpi

mpirun ~/opt/eman2-unstable/examples/mpi_test.py
