#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2tomogram
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=4g
#
#SBATCH --time=24:00:00
#

ref="$1"; shift
particles="$1"; shift

project="`pwd | sed 's/.*work\///g'`"

echo "Beginning refinement on $project

Reference: $ref
Particles: $particles" | notify_slack -username "SDF $project"

. ~/opt/eman2-unstable/bin/activate

e2spt_refinemulti_new.py $ref --ptcls $particles --niter 10 --maxres 20 --parallel threads:32 | notify_slack -username "SDF $project"

echo "Finished refinement on $project

`times`" | notify_slack -username "SDF $project"
