#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=e2tomogram
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=32
#SBATCH --mem-per-cpu=16g
#
#SBATCH --time=24:00:00
#

. ~/opt/eman2-unstable/bin/activate

e2tomogram.py --alltiltseries --zeroid=-1 --tltstep=2.0 --rawtlt=rawtlt --mdoc=mdocs --npk=20 --tltax=85.2 --tltkeep=0.9 --outsize=1k --niter=2,1,1,1 --bytile --notmp --pkkeep=0.9 --compressbits=8 --clipz=-1 --bxsz=32 --filterres=40.0 --rmbeadthr=10.0 --threads=32 --patchtrack=1
