#!/bin/bash

#SBATCH --partition=cryoem
#
#SBATCH --job-name=make-annot
#SBATCH --output=output-%j.txt
#SBATCH --error=output-%j.txt
#
#SBATCH --ntasks=24
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=2g
#
#SBATCH --time=24:00:00
#

. e2-header

for foo in $@; do
  srun --ntasks=1 --nodes=1 --cpus-per-task=$SLURM_CPUS_PER_TASK annotate-movie $foo &
done

wait

. e2-footer
